
defaults:
  - _self_
  # - config: ???

config:
  method:
    name: er
    supervised: true    

  model:
    name: resnet18
    nf: 32
    use_snapshots: false
    save_snapshots: false
    snapshots_path: ./snapshots/

  train:
    scenario: class_incremental
    batch_size: 32
    buffer_batch_size: 32
    epochs: 1
    iters: 1
    use_augs: false
    task_free: false
    mem_size: 0
    optim:
      name: sgd
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
      lr_decay_rate: 0.1
      lr_decay_epochs: 120,160

  eval:
    scenario: class_incremental # instead of singlelinear and multilinear
    probe_eval: false # instead of keep_training_data
    cka_eval: false
    eval_layer: -1
    eval_every: 1e9
    epochs: 1
    optim:  
      name: sgd
      lr: 0.01

  data:
    dataset: cifar10
    root: ../cl-datasets/data/
    download: true
    smooth: false

  logging:
    exp_name: tmp
    wandb_log: false
    wandb_project: ???
    log_path: ./outputs/

